# Generated by Django 5.0.2 on 2024-09-12 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Forms', '0001_initial'),
        ('Projects', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_DBTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nome da ação')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID do Ativo/Elemento?')),
                ('priority', models.CharField(choices=[('Baixa', 'Baixa'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=100, verbose_name='Prioridade')),
                ('deadline', models.DateField(null=True, verbose_name='Data limite')),
                ('place', models.CharField(max_length=100, verbose_name='Local')),
                ('description', models.TextField(max_length=2000, verbose_name='Descrição')),
                ('questionKey', models.CharField(max_length=100, null=True, verbose_name='Chave da pergunta')),
                ('status', models.CharField(choices=[('Nova', 'Nova'), ('Em andamento', 'Em andamento'), ('Concluida', 'Concluida'), ('Cancelada', 'Cancelada')], default='Nova', max_length=100, verbose_name='Status')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Ativo ou Elemento')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to=settings.AUTH_USER_MODEL)),
                ('user_hasCreated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hasCreated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset_DBTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetName', models.CharField(max_length=100, verbose_name='Nome do ativo')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Arquivado', 'Arquivado')], default='Ativo', max_length=100, verbose_name='Status')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.form')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.project_dbtable')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_DBTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=2000, verbose_name='Comentário')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID do Ativo/Elemento?')),
                ('questionKey', models.CharField(max_length=100, null=True, verbose_name='Chave da pergunta')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Ativo ou Elemento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ativos/', verbose_name='Foto')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='Descrição')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID do Ativo/Elemento?')),
                ('questionKey', models.CharField(max_length=100, null=True, verbose_name='Chave da pergunta')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Ativo ou Elemento')),
            ],
        ),
        migrations.CreateModel(
            name='SubItem_DBTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementName', models.CharField(max_length=100, verbose_name='nome do elemento')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrations.asset_dbtable')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.form')),
            ],
        ),
        migrations.CreateModel(
            name='Asset_Sub_Element_DBTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSubElement', models.CharField(max_length=100, verbose_name='nome do subElemento')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.form')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registrations.subitem_dbtable')),
            ],
        ),
    ]
