# Generated by Django 5.0.2 on 2024-11-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
