# Generated by Django 5.0.2 on 2024-11-26 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser_dbtable',
            name='lastConnection',
            field=models.DateField(default=datetime.datetime.now, null=True, verbose_name='Última conexão'),
        ),
    ]
