# Generated by Django 5.0.2 on 2024-09-12 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser_dbtable',
            name='lastConnection',
            field=models.DateField(default=datetime.datetime.now, null=True, verbose_name='Ultima conexao'),
        ),
        migrations.AddField(
            model_name='customuser_dbtable',
            name='registrationDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data de registro'),
        ),
    ]
