# Generated by Django 5.0.2 on 2024-11-27 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_customuser_dbtable_lastconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_dbtable',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
