# Generated by Django 5.0.2 on 2024-10-21 04:54

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_customuser_dbtable_lastconnection_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_dbtable',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser_dbtable',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customusuario_groups', related_query_name='customusuario', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser_dbtable',
            name='lastConnection',
            field=models.DateField(default=datetime.datetime.now, null=True, verbose_name='Última conexão'),
        ),
        migrations.AlterField(
            model_name='customuser_dbtable',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customusuario_user_permissions', related_query_name='customusuario', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
