name: Deploy Django Application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'  # Ou a versão que sua aplicação requer

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gdif:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/gdif:latest

      - name: Stop and remove existing container
        run: |
          docker stop gdif || true
          docker rm gdif || true

      - name: Run Docker container
        run: |
          docker run -d \
          -p 8000:8000 \
          -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
          -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
          -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
          --name wisetime \
          ${{ secrets.DOCKER_USERNAME }}/gdif:latest
